### ISSUE TITLE
Property widget: Property list not rendered when selection changes rapidly

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#713]
Reproduced by flaky e2e tests:
- `multiple elements selected`
- `multiple elements selected - search bar expanded`

Looks like the problem is that the second node is selected while properties for the first one are not loaded yet, which causes the properties for final selection to not load either.
```[tasklist]
### Tasks
- [ ] Header should show label of last selected item (https://github.com/iTwin/viewer-components-react/pull/717)
- [ ] Spinner is not visible when property grid is rendered in widget
- [ ] https://github.com/iTwin/appui/issues/641
```

**Comment by grigasp** [comment]
Need to update test viewer and property widget (dev)dependencies, re-run e2e tests to ensure nothing is broken. Putting this on hold till the fix is released.
