### ISSUE TITLE
Tree widget: Tests

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#847]
```[tasklist]
### Tasks
- [ ] https://github.com/iTwin/viewer-components-react/pull/875
- [ ] https://github.com/iTwin/viewer-components-react/pull/872
- [ ] https://github.com/iTwin/viewer-components-react/pull/871
- [ ] https://github.com/iTwin/viewer-components-react/pull/898
```
